CHANGELOG.md, package.json, src/cli/api/api.ts, src/cli/api/trackingplans.ts, src/cli/commands/build.tsx, src/generators/android/templates/RudderTyperUtils.java.hbs, src/generators/gen.ts, src/generators/javascript/templates/index.hbs, src/generators/objc/templates/RSRudderTyperUtils.m.hbs, src/generators/swift/swift.ts, src/generators/swift/templates/RudderTyperUtils.swift.hbs
=> Added Additional Context and Made Optional Values defaulted to nil in Swift

package.json, src/generators/javascript/templates/index.hbs
=> Draft 04 JSON Schema support

example/package.json, package.json, src/generators/android/android.ts, src/generators/gen.ts, src/generators/javascript/javascript.ts, src/generators/objc/objc.ts, src/generators/swift/swift.ts
=> Changing Naming Convention of Objects to improve the experience

.gitignore, example/analytics/plan.json, example/index.js, example/index.ts, example/package.json, example/ruddertyper.yml, package.json, src/cli/commands/init.tsx, src/generators/javascript/javascript.ts, src/generators/javascript/templates/index.hbs, src/generators/javascript/templates/rudder.hbs, src/generators/options.ts
=> Added TypeScript Support for RudderTyper

.github/workflows/code-coverage.yml, .github/workflows/tests.yml, .gitignore, codecov.yml, package.json
=> chore: codecov added

package.json, src/cli/api/api.ts, src/cli/api/trackingplans.ts, src/cli/commands/build.tsx, src/cli/commands/init.tsx, src/cli/commands/version.tsx, src/cli/config/config.ts, src/cli/index.tsx, src/cli/types.ts, tsconfig.json
=> fix: add typescript types for build

.prettierrc.json, package.json, src/generators/javascript/javascript.ts, src/generators/javascript/templates/index.hbs
=> feat: update package for prod

src/generators/javascript/templates/index.hbs
=> fix: update import statement

.prettierrc.json, package.json, src/generators/javascript/javascript.ts, src/generators/javascript/templates/index.hbs, src/generators/javascript/templates/rudder.hbs
=> chore: backmerge master to develop

.github/workflows/draft-new-release.yml
=> fix: draft new release for histories

.github/workflows/draft-new-release.yml
=> fix: draft new release for histories 2

.github/workflows/draft-new-release.yml
=> fix: draft new release for histories 3

.github/workflows/draft-new-release.yml
=> fix: draft new release for histories 4

.github/workflows/draft-new-release.yml
=> feat: draft new release 5

src/generators/javascript/templates/rudder.hbs
=> fix: node sdk passing either userid or anonid

README.md, example/ruddertyper.yml, src/cli/api/trackingplans.ts, src/cli/commands/help.tsx, src/cli/commands/init.tsx, src/cli/config/ruddertyper.yml.hbs
=> chore: update docs and links

src/generators/javascript/templates/index.hbs
=> fix: pass tracking plan version as int

.github/ISSUE_TEMPLATE.md, README.md
=> chore: update rudder-typer template

package-lock.json, src/cli/api/api.ts, src/cli/api/trackingplans.ts, src/cli/commands/build.tsx, src/cli/commands/init.tsx, src/cli/config/ruddertyper.yml.hbs, src/cli/config/schema.ts, src/generators/gen.ts
> Add support for mode during `init` phase whether the code generated will be for production or development
show the Tracking Plan version in the summary and .yml file
- Focus on what is best for the …
=> feat: add version and mode support for init

package-lock.json, package.json
=> chore(release): pulling release/1.0.0-beta.10 into master

package-lock.json, package.json
=> chore(release): pulling release/1.0.0-beta.11 into master

.github/workflows/draft-new-release.yml, package-lock.json, package.json
> add changelog during release
=> feat: add changelog during release

.github/workflows/draft-new-release.yml, package.json
> stable release number 1.0.0 and remove from beta
=> chore: stable release number 1.0.0

.github/workflows/draft-new-release.yml
> revert to conventional workflow for version bump
=> chore: revert to conventional workflow

.github/workflows/draft-new-release.yml, CHANGELOG.md, package.json
> commit changes for changelog
npx standard-version auto bumps the version and creates a changelog
say from v1.0.0 -> v1.1.1 and adds changelog for it
- Show …
=> chore: commit changes for changelog

.github/workflows/publish-new-release.yml
> create github release action
=> chore: create github release

src/cli/api/api.ts
> add user-agent in header for API Usage metric 
[DAT-1696](https://linear.app/rudderstack/issue/DAT-1696/pass-useragent-for-get-tp-api-in-ruddertyper)
- Show …
=> chore: add useragent for api usage

src/cli/api/api.ts
> Fixed import assertion type missing error
=> fix: import assertion error

README.md, src/cli/config/schema.ts
> update readme file for troubleshooting and schema validation for version v1 and v2
=> fix: update readme and schema validation for version

src/generators/android/android.ts, src/generators/javascript/javascript.ts, src/generators/utils.ts
> handle enum names i.e replace hypes with underscore and remove special characters
=> fix: handle enum names variable

.github/workflows/publish-new-release.yml
> update workflow for github release
=> chore: update workflow for github release

src/generators/android/android.ts, src/generators/javascript/javascript.ts, src/generators/utils.ts
=> fix: sanitize enum key

src/generators/android/templates/class.java.hbs
> enum insertion for android SDK
=> fix: enum insertion for android sdk

src/generators/android/android.ts, src/generators/ast.ts, src/generators/gen.ts, src/generators/javascript/javascript.ts
> add nested prop for array `any` type and enum support for union fields
=> fix: add nested prop for array type any and enum for union

CHANGELOG.md, package-lock.json, package.json, src/generators/android/android.ts, src/generators/android/templates/class.java.hbs, src/generators/ast.ts, src/generators/gen.ts, src/generators/javascript/javascript.ts, src/generators/utils.ts
=> chore(release): pulling release/1.3.2 into master

src/generators/javascript/templates/index.hbs, src/templates.ts
=> fix: make field enum namespaced

src/generators/android/android.ts, src/generators/android/templates/RudderTyperAnalytics.java.hbs, src/generators/android/templates/RudderTyperUtils.java.hbs, src/generators/android/templates/class.java.hbs
> fix android app null exception
=> fix: android null exception

README.md
> update readme docs for precedence workflow for client and scripts
=> chore: update readme docs for precedence workflow for client and scripts

README.md
=> chore: update readme docs

src/generators/android/android.ts, src/generators/javascript/javascript.ts, src/generators/javascript/templates/index.hbs, src/generators/swift/swift.ts, src/generators/swift/templates/analytics.swift.hbs, src/generators/swift/templates/class.swift.hbs, src/generators/swift/templates/functionDocumentation.hbs, src/generators/utils.ts
> add enum support for swift language iOS 
make enum name unique based on property name + property type
refactor enum for android
- Show empathy toward other …
=> feat: add enum support for swift language iOS

CHANGELOG.md, README.md, package-lock.json, package.json, src/cli/api/api.ts, src/generators/android/android.ts, src/generators/javascript/javascript.ts, src/generators/javascript/templates/index.hbs, src/generators/swift/swift.ts, src/generators/swift/templates/analytics.swift.hbs, src/generators/swift/templates/class.swift.hbs, src/generators/swift/templates/functionDocumentation.hbs, src/generators/utils.ts
=> chore(release): pulling release/1.5.0 into master

src/generators/android/android.ts, src/generators/android/templates/class.java.hbs
> Please provide a detailed description of the changes you’ve made in this section. Clearly explain what has been modified, added, or removed, and how it impacts the overall project.
- Focus on what is …
=> fix: handle field nullability

src/generators/swift/templates/analytics.swift.hbs, src/generators/swift/templates/class.swift.hbs
> Please provide a detailed description of the changes you’ve made in this section. Clearly explain what has been modified, added, or removed, and how it impacts the overall project.
- Focus on what is …
=> chore: show description for events and properties in multiline

CHANGELOG.md, package-lock.json, package.json, src/generators/swift/templates/analytics.swift.hbs, src/generators/swift/templates/class.swift.hbs
=> chore(release): pulling release/1.5.2 into master

src/generators/swift/templates/analytics.swift.hbs, src/generators/swift/templates/class.swift.hbs
> refactor swift SDK for docstring and enums
=> chore: refactor swift SDK

src/cli/commands/build.tsx
> This PR improves the error messages in `rudder-typer` when credentials are missing or when the tracking plan cannot be fetched.
Changes Made
- Enhanced error message for missing API credentials by explicitly listing the missing items (API token, email).
- Updated instructions to prompt users to run `rudder-typer init` when credentials are missing.
- Improved error handling when the tracking plan cannot be …
=> fix: improve error message for failure

CHANGELOG.md, package-lock.json, package.json, src/cli/commands/build.tsx, src/generators/android/android.ts, src/generators/ast.ts, src/generators/gen.ts, src/generators/javascript/javascript.ts, src/generators/objc/objc.ts, src/generators/swift/swift.ts, src/generators/swift/templates/analytics.swift.hbs, src/generators/swift/templates/class.swift.hbs
=> chore(release): pulling release/1.5.3 into master

src/generators/android/templates/class.java.hbs, src/generators/ast.ts, src/generators/gen.ts, src/generators/javascript/templates/index.hbs, src/generators/objc/templates/class.h.hbs, src/generators/swift/templates/class.swift.hbs, src/generators/swift/templates/functionDocumentation.hbs, src/templates.ts
> This PR improves docstring generation by adding structured validation rule annotations, ensuring clarity and type safety. The enhanced docstrings now explicitly define constraints such as maxLength, minLength, maximum, minimum, 
exclusiveMaximum, exclusiveMinimum etc.
eg:
```
/**
* Advanced Validation Rules:
*
* - maxLength: `20` → Maximum allowed characters.
* - minLength: `2` → Minimum required characters.
* …
```
=> feat: add advanced keywords docstring

CHANGELOG.md, package-lock.json, package.json, src/cli/api/api.ts, src/cli/commands/init.tsx, src/generators/android/templates/class.java.hbs, src/generators/ast.ts, src/generators/gen.ts, src/generators/javascript/templates/index.hbs, src/generators/objc/templates/class.h.hbs, src/generators/swift/templates/class.swift.hbs, src/generators/swift/templates/functionDocumentation.hbs, src/templates.ts
=> chore(release): pulling release/1.6.0 into master

src/cli/commands/init.tsx, src/generators/ast.ts
> Add identity support for context-traits & sort Tracking Plans by lastUpdatedAt during init
=> fix: add identity for context - traits

src/generators/gen.ts
> update advanced keywords docstring
=> chore: update advanced keywords docstring

CHANGELOG.md, examples/node-javascript/package-lock.json, examples/node-javascript/package.json, examples/node-typescript/package-lock.json, examples/node-typescript/package.json, package-lock.json, package.json, src/cli/commands/init.tsx, src/generators/ast.ts, src/generators/gen.ts
=> chore(release): pulling release/1.7.0 into master

src/cli/config/schema.ts, src/generators/gen.ts
> Removed defSupport validation from both client and trackingPlan configurations in schema
Removed corresponding early return check in generation logic
Changed schema validation to convert: false to prevent automatic value transformation
Updated return value to use original rawConfig instead of transformed result.value
- Use …
=> fix: remove def support schema validation inconsistency

CHANGELOG.md, package-lock.json, package.json, src/cli/config/schema.ts, src/generators/gen.ts
=> chore(release): pulling release/1.8.0 into master

examples/node-javascript/package.json, examples/node-typescript/package.json
=> chore(release): pulling master into develop post release v1.7.2
